.travis.yml, lib/client.js, lib/http-client.js, lib/listeners/message/http-title.js, lib/listeners/message/scala.js, lib/scala.js, sectery.js, test/sectry_test.js
This makes tests run **so much faster**.  Fixes #4.
Usage: some code (e.g. the @scala message listener) asks for one of the abstracted clients (e.g. the scala client), and it gets a mock one if the IRC_PROD env var is not set to *true*, else it gets the production one that goes out to the real Internets.
=> Create mock/prod versions of some things

lib/sectery.js
Based on [these recommendations][1]:
> The rule of thumb is 2 seconds per line, and that includes lines
> without content, like PINGs. The algorithm allows for bursts up to 5
> at once (in a 10 second span).
This could use some refactoring for beauty, but the idea is to send
replies every 250ms, without exceeding five messages in a ten second
span.
This mostly ignores the *2 seconds per line* guideline, since that is
covered by *up to 5 in a 10 second span*.  I'm not sure whether that's
bending the rules.
[1]: https://www.reddit.com/r/irc/comments/1rdejj/freenode_flood_limits/cdm7jo9
=> Allow message bursts of up to five at a time

lib/listeners/message/ascii-text.js
```text
@ascii blink foo
```
worked, but not
```text
@ascii foo
```
do to previous regex looking for two spaces minimum before the text, when blink option was absent.
=> Fix ascii blink regex to match non blink command

README.md, src/main/scala/sectery/MessageQueues.scala, src/test/scala/sectery/MessageQueuesSpec.scala
This sets up a queue for incoming messages received from IRC, a queue
for outgoing messages to be throttled and sent to IRC, a process for
reading and responding to messages, and a loop to manage the whole
thing.
=> Add a ZIO-based message queueing system

src/main/scala/sectery/MessageQueues.scala, src/test/scala/sectery/MessageQueuesSpec.scala
This introduces [`zio.clock.Clock`][1] into the environment of the
message producer so that we can manage time during testing to write
deterministic tests.
[1]: https://javadoc.io/static/dev.zio/zio_2.12/1.0.8/zio/clock/index.html#Clock=zio.Has[zio.clock.package.Clock.Service]
=> Add support for @time

src/main/scala/sectery/Bot.scala, src/main/scala/sectery/Sectery.scala
This swaps out the sample PircBotX listener adapter with the ZIO-based
inbox/producer/outbox message queuing system, and hooks it up to the bot
instance.
=> Connect the IRC bot to the message queueing system

src/main/scala/sectery/Bot.scala
This allows early authentication with NickServ upon connection.
For details, see https://github.com/pircbotx/pircbotx/wiki/Documentation#sasl-authentication
=> Add configuration for SASL-based authentication

README.md, src/main/scala/sectery/MessageQueues.scala, src/main/scala/sectery/Producer.scala, src/main/scala/sectery/producers/Ping.scala, src/main/scala/sectery/producers/Time.scala
This takes the quickly-growing pattern match in `Producer.apply`, and
splits it into individual classes under the `sectery.producers` package.
Adding new producers now consists of writing a new `Producer`
implementation, and then adding it to the list of producers in
`Producer.producers`.
=> Extract message producers into their own classes

src/main/scala/sectery/Http.scala, src/main/scala/sectery/MessageQueues.scala, src/main/scala/sectery/Producer.scala, src/main/scala/sectery/Sectery.scala, src/main/scala/sectery/producers/Eval.scala, src/test/scala/sectery/MessageQueuesSpec.scala
This adds support for `@eval`, which passes its argument to Haskeval.
This also adds a new ZIO service for making HTTP requests, and a way to
mock responses for ZIO Test.
=> Add support for @eval and an HTTP service for ZIO

src/main/scala/sectery/Http.scala, src/main/scala/sectery/producers/Eval.scala
The Http.live  implementation uses a lot of the `java.net._` API, which
throws all kinds of exceptions.  This changes the effect type
accordingly, so that if something goes wrong we can decide how to handle
it from within the `Producer` implementation.  For now, we shrug it off
and do nothing.
=> Change Http.Service.request from UIO to Task

src/test/scala/sectery/MessageQueuesSpec.scala, src/test/scala/sectery/TestHttp.scala
This better reflects the structure in *src/main* and removes some noise
from *MessagesQueuesSpec.scala*.
=> Extract TestHttp into its own file

src/main/scala/sectery/Producer.scala, src/main/scala/sectery/producers/Html.scala, src/test/scala/sectery/MessageQueuesSpec.scala
This detects http(s) URLs, fetches them, and tries to pull out a
description or title to respond to the channel with.  This uses a lot of
hacktastic regexes, but it kind of works.  A follow-up could be
replacing the regexes with a civilized HTML parser.
=> Add support for describing HTML from http(s) URLs

src/main/scala/sectery/producers/Html.scala
Some CDNs throw a 403 if they receive a request without a User-Agent
header.  This sets it to `bot` just so that it's non-empty.
=> Add a non-empty User-Agent header

build.sbt, src/main/scala/sectery/producers/Html.scala
This uses an actual HTML parser to look for page metadata, which will
have a better hit rate than any set of regular expressions.
=> Replace HTML regex parsing with jsoup

src/main/scala/sectery/Producer.scala, src/main/scala/sectery/producers/Substitute.scala, src/test/scala/sectery/MessageQueuesSpec.scala
1. Enable it in `Producer.producers`
2. Add a test
3. Don't limit candidates to the nick sending the regex
4. Save the updated per-nick messages data
=> Get the regex substitution producer working

src/main/scala/sectery/producers/Substitute.scala, src/test/scala/sectery/MessageQueuesSpec.scala
This fixes a bug where `Substitute` will try to replace any message
received, regardless of whether it matches the replacement pattern.
=> Apply substitute to the first matching message

build.sbt, src/main/scala/sectery/Db.scala, src/main/scala/sectery/MessageQueues.scala, src/main/scala/sectery/Producer.scala, src/main/scala/sectery/Sectery.scala, src/main/scala/sectery/producers/Count.scala, src/main/scala/sectery/producers/Eval.scala, src/main/scala/sectery/producers/Html.scala, src/main/scala/sectery/producers/Ping.scala, src/main/scala/sectery/producers/Time.scala, src/test/scala/sectery/MessageQueuesSpec.scala, src/test/scala/sectery/TestDb.scala
This adds a new database service `Db` that wraps SQLite, and a producer
that responds to `@count` as an example of how to use it.
It's currently up to each producer to deal with isolation from other
producers, and between channels and nicks, as well as transaction
management.  These are all potential areas for improvement of the
`Db` service.
=> Add support for SQLite persistence, @count

src/test/scala/sectery/MessageQueuesSpec.scala
This test can fail depending on the order of execution of the other
tests, as the "last message" entry can be overwritten by the "bar" user
in the same channel on another test.
=> Isolate tests for Substitute to own IRC channel

src/main/scala/sectery/Finnhub.scala, src/main/scala/sectery/MessageQueues.scala, src/main/scala/sectery/Producer.scala, src/main/scala/sectery/Sectery.scala, src/main/scala/sectery/producers/Stock.scala, src/test/scala/sectery/TestFinnhub.scala, src/test/scala/sectery/producers/Count.scala, src/test/scala/sectery/producers/Eval.scala, src/test/scala/sectery/producers/Html.scala, src/test/scala/sectery/producers/Ping.scala, src/test/scala/sectery/producers/Stock.scala, src/test/scala/sectery/producers/Substitute.scala, src/test/scala/sectery/producers/Time.scala, src/test/scala/zio/Inject.scala
This includes a new service `Finnhub` that requires an environment
variable `FINNHUB_API_TOKEN` in the live implementation.  This also
replaces the ever-growing `Finnhub.Finnhub with Db.Db with Http.Http
with Clock` envrionment type with a type alias `Producer.Env` for
brevity.
=> Add support for @stock

src/main/scala/sectery/Sectery.scala, src/main/scala/sectery/producers/Count.scala, src/main/scala/sectery/producers/Eval.scala, src/main/scala/sectery/producers/Html.scala, src/main/scala/sectery/producers/Stock.scala
This logs at the error level all exceptions caught by a `catchAll`.
=> Add error logging of caught exceptions

src/main/scala/sectery/producers/Stock.scala, src/test/scala/sectery/producers/Stock.scala
This relaxes the restriction on the user to format stock symbols using
all caps.
=> Automatically capitalize stock symbols on lookup

src/main/scala/sectery/Db.scala
This allows the DB file to be placed outside of `$PWD`.
=> Use an env var for the database path

src/main/scala/sectery/Db.scala
Configuring the database path via an env var was added in #167, but
without interpolation the connection string fails to use it.  This fixes
that.
=> Don't forget to actually interpolate the string

build.sbt, src/main/scala/sectery/Producer.scala, src/main/scala/sectery/producers/Weather.scala, src/test/scala/sectery/producers/WeatherSpec.scala
This adds support for `@wx <location>`, which gets the current weather
at the given location.
OpenStreetMap is used to search for the location, and DarkSky is used to
get weather by lat/lon.  Json4s is used for parsing JSON responses from
both.  DarkSky requires an API key, which must be set in the
`DARK_SKY_API_KEY` environment variable.
=> Add support for looking up the weather report

src/main/scala/sectery/Producer.scala, src/main/scala/sectery/producers/Count.scala, src/main/scala/sectery/producers/Eval.scala, src/main/scala/sectery/producers/Html.scala, src/main/scala/sectery/producers/Ping.scala, src/main/scala/sectery/producers/Stock.scala, src/main/scala/sectery/producers/Substitute.scala, src/main/scala/sectery/producers/Time.scala, src/main/scala/sectery/producers/Weather.scala, src/test/scala/sectery/producers/Help.scala
This updates the `Producer` trait to include a list of `@commands` that
it responds to, which are reported when the user types `@help`.
=> Add a rudimentary @help command to list commands

src/main/scala/sectery/Producer.scala, src/main/scala/sectery/producers/Count.scala, src/main/scala/sectery/producers/Eval.scala, src/main/scala/sectery/producers/Html.scala, src/main/scala/sectery/producers/Ping.scala, src/main/scala/sectery/producers/Stock.scala, src/main/scala/sectery/producers/Substitute.scala, src/main/scala/sectery/producers/Time.scala, src/main/scala/sectery/producers/Weather.scala, src/test/scala/sectery/producers/Help.scala
This expands the `@help` registration mechanism to take both a name and
a message about usage info.  Users can still get the list of supported
patterns via `@help`, but can now also get specific usage information
via `@help @foo`.
=> Expand @help to include usage information

src/main/scala/sectery/Producer.scala, src/main/scala/sectery/producers/Btc.scala, src/test/scala/sectery/producers/BtcSpec.scala, src/test/scala/sectery/producers/HelpSpec.scala
This introduces a simple CoinDesk API client, and a message producer
that responds to `@btc` with the current BTC rate in USD.
Fixes #174
=> Add support for @btc

.github/workflows/scala.yml, .scalafix.conf, build.sbt, project/plugins.sbt, src/main/scala/sectery/Bot.scala, src/main/scala/sectery/MessageQueues.scala, src/main/scala/sectery/Producer.scala, src/main/scala/sectery/Sectery.scala, src/main/scala/sectery/producers/Btc.scala, src/main/scala/sectery/producers/Eval.scala, src/main/scala/sectery/producers/Html.scala, src/main/scala/sectery/producers/Ping.scala, src/main/scala/sectery/producers/Stock.scala, src/main/scala/sectery/producers/Time.scala, src/main/scala/sectery/producers/Weather.scala, src/test/scala/sectery/producers/BtcSpec.scala, src/test/scala/sectery/producers/CountSpec.scala, src/test/scala/sectery/producers/EvalSpec.scala, src/test/scala/sectery/producers/HelpSpec.scala, src/test/scala/sectery/producers/HtmlSpec.scala, src/test/scala/sectery/producers/PingSpec.scala, src/test/scala/sectery/producers/StockSpec.scala, src/test/scala/sectery/producers/SubstituteSpec.scala, src/test/scala/sectery/producers/TimeSpec.scala, src/test/scala/sectery/producers/WeatherSpec.scala
This adds [sbt-scalafix][0], [OrganizeImports][1], and a CI step to
check whether sources have had their imports organized.  This also
applies OrganizeImports, so that the CI check will pass.
[0]: https://scalacenter.github.io/scalafix/
[1]: https://github.com/liancheng/scalafix-organize-imports
=> Add sbt-scalafix and enable OrganizeImports

build.sbt, src/main/scala/sectery/Producer.scala, src/main/scala/sectery/producers/Weather.scala, src/test/scala/sectery/producers/WeatherSpec.scala
This adds an AirNow API client to retrieve Air Quality Index info as
part of weather info produced via `@wx`.  The client is added as a new
`AirNow` object.  This also refactors the location and forecast
retrieval into the `OSM` and `DarkSky` objects.
Fixes #176
=> Add Air Quality Index to @wx

src/main/scala/sectery/producers/Weather.scala, src/test/scala/sectery/producers/WeatherSpec.scala
For certain locations, the AQI current observation doesn't always return
an empty array.  For those same locations, the AQI forecast does
sometimes return something usable.
This changes the AQI retrieval process to include both the current
observation and the forecast, combining the first values found from each
to produce the final result.
=> Use the AQI forecast in addition to observation

src/main/scala/sectery/producers/Weather.scala, src/test/scala/sectery/producers/WeatherSpec.scala
This updates the Dark Sky `/forecast` parser to include the first entry
in `daily.data`, pull out the low and high temperature forecast for the
day, and include them in the response to `@wx`.
Fixes #184
=> Include weather forecast in response to @wx

src/test/resources/com/coindesk/api/v1/bpi/currentprice.json, src/test/scala/sectery/Resource.scala, src/test/scala/sectery/producers/BtcSpec.scala
This tidies up the @btc test code by moving the big block of JSON from
the Scala source to a *.json* file under src/test/resources.  The
*.json* file includes the full response from the CoinDesk API, rather
than the truncated version in *BtcSpec.scala*, which makes for a more
accurate test and will be useful for future reference.
This also adds a utility to read in a string given a path on the
classpath.
=> Move CoinDesk sample response to a .json file

src/main/scala/sectery/producers/Weather.scala, src/test/scala/sectery/producers/WeatherSpec.scala
This shortens the growing output produced by @wx to make it a bit more
readable:
```
San Francisco, San Francisco City and County, San Francisco, California, United States: temperature 60° (low 53°, high 63°), humidity 1.0%, wind 5.6 mph, UV index 0, O3: 15/Good, PM2.5: 0/Good
San Francisco: 60° (low 53°, high 63°), humidity 1%, wind 6 mph, UV 0, O3 15 (Good), PM2.5 0 (Good)
```
=> Condense the output from @wx

.github/workflows/build.yml, .github/workflows/deploy.yml, Procfile, build.sbt, project/plugins.sbt, src/main/resources/logback.xml, src/main/scala/sectery/Db.scala, src/main/scala/sectery/producers/Substitute.scala
This makes a few changes to allow sectery to deploy to and run on
Heroku:
* Drop unused forked runtime environment variables, since these are
inherited from the parent environment
* Change root log level from `info` to `warn` to limit volume and exposure
* Add support for Postgres, and use it for production
* https://devcenter.heroku.com/articles/heroku-postgresql#connecting-in-java
* Use sbt-native-packager to package as a Java app, with scripts
generated in *target/universal/stage/bin/*
* Configure as a `worker` Heroku process type
* https://devcenter.heroku.com/articles/procfile#other-process-types
* Deploy to Heroku when changes are pushed to the `master` branch
=> Configure continuous deployment to Heroku

build.sbt, project/plugins.sbt, src/main/scala/sectery/Producer.scala, src/main/scala/sectery/producers/Version.scala, src/test/scala/sectery/producers/HelpSpec.scala, src/test/scala/sectery/producers/VersionSpec.scala
This uses [sbt-git][1] to compute version information at build time and
[sbt-buildinfo][2] to make it available at compile time and runtime.
This also adds a new `Version` producer which uses these to respond to
`@version` messages with the current version of sectery.
[1]: https://github.com/sbt/sbt-git
[2]: https://github.com/sbt/sbt-buildinfo
=> Add support for looking up the current version

src/main/scala/sectery/Producer.scala, src/main/scala/sectery/producers/Zillow.scala, src/test/scala/sectery/producers/HelpSpec.scala, src/test/scala/sectery/producers/ZillowSpec.scala
This adds a new producer that responds to `@zillow <address>` by looking
up the address on Zillow and searching for the Zestimate for that
address.
=> Add a Zillow scraper to search for Zestimates

src/main/resources/logback.xml
This adds support for an optional `LOG_LEVEL_ROOT` environment variable
to set the root log level.  If absent, it defaults to `WARN`.
=> Allow root log level config via env var

src/main/scala/sectery/producers/Zillow.scala
This will help prevent captcha redirects.
=> Replace the Zillow user agent with Mozilla/5.0

src/main/scala/sectery/producers/Btc.scala, src/main/scala/sectery/producers/Eval.scala, src/main/scala/sectery/producers/Html.scala, src/main/scala/sectery/producers/Weather.scala, src/main/scala/sectery/producers/Zillow.scala
This updates the producers that make HTTP responses to log an error when
they receive an unexpected response.
=> Log unexpected HTTP responses

src/main/scala/sectery/producers/Btc.scala, src/main/scala/sectery/producers/Eval.scala, src/main/scala/sectery/producers/Html.scala, src/main/scala/sectery/producers/Weather.scala, src/main/scala/sectery/producers/Zillow.scala
This is a follow-up to #198 to make sure that the response itself is
included in the log message.
=> Include the unexpected response in the log message

src/main/scala/sectery/producers/Html.scala, src/test/scala/sectery/producers/HtmlSpec.scala
The description isn't always the most relevant descriptor.  This
switches to grabbing the title instead.  A follow-up to this could be
site-specific switching between title and description.
=> Switch HTML parser to look for the title

src/main/scala/sectery/producers/Weather.scala, src/test/scala/sectery/producers/WeatherSpec.scala
The Dark Sky API appears to give humidity as a value between zero and
one, but we have been treating it as a value between zero and 100.
This updates the parser to treat the value as a percentage rather than a
fraction.
=> Parse humidity as a value from zero to one

src/main/scala/sectery/producers/Html.scala, src/test/scala/sectery/producers/HtmlSpec.scala
First we looked for the description, then we switched to the title.  It
seems neither is reliably sufficient.  This updates the HTML parser to
look for both.
=> Update HTML parser to find title and description

src/main/scala/sectery/Bot.scala, src/main/scala/sectery/MessageQueues.scala, src/main/scala/sectery/Sectery.scala
This prevents `PircBotX.startBot()`, which blocks the calling thread,
from blocking subsequent effects by wrapping it in `IO#succeedBlocked`.
=> Don't allow PircBotX to block the main thread

src/main/scala/sectery/Producer.scala, src/main/scala/sectery/producers/Tell.scala, src/test/scala/sectery/producers/HelpSpec.scala, src/test/scala/sectery/producers/TellSpec.scala
This allows a user to leave a message for another user, which they will
receive the next time they say something.
For example:
```
<user1> @tell user2 Howdy
<sectery> I will let them know.
<user2> Hey
<sectery> user2: on 1970-02-11, user1 said: Howdy
```
Fixes #210
=> Add support for @tell

src/main/scala/sectery/producers/Tell.scala, src/test/scala/sectery/producers/TellSpec.scala
This prevents the nick group from matching on spaces, which would break
@tell for messages with more than one word.
=> Make the @tell regex nick group less greedy

src/main/scala/sectery/producers/Tell.scala, src/test/scala/sectery/producers/TellSpec.scala
This sorts messages from @tell by date, so that they play back in
chronological order.
=> Order @tell messages chronologically

src/main/scala/sectery/Producer.scala, src/main/scala/sectery/producers/LastMessage.scala, src/main/scala/sectery/producers/Substitute.scala
The `LAST_MESSAGE` table will be useful for more than just substitution,
and this change makes it more easier to reason about and maintain the
table as separate from the substitution producer.
=> Extract "last message" logging into own producer

build.sbt
Something changed between M2 and M3 that's causing blocking with the
current approach.  Rolling back to M2 until it can be addressed.
=> Rollback zio to 2.0.0-M2

src/main/scala/sectery/Db.scala, src/main/scala/sectery/Finnhub.scala, src/main/scala/sectery/Producer.scala, src/main/scala/sectery/Sectery.scala, src/main/scala/sectery/producers/Btc.scala, src/main/scala/sectery/producers/Count.scala, src/main/scala/sectery/producers/Eval.scala, src/main/scala/sectery/producers/Grab.scala, src/main/scala/sectery/producers/Html.scala, src/main/scala/sectery/producers/LastMessage.scala, src/main/scala/sectery/producers/Stock.scala, src/main/scala/sectery/producers/Substitute.scala, src/main/scala/sectery/producers/Tell.scala, src/main/scala/sectery/producers/Weather.scala
This moves most of the `catchAll` blocks out of the individual
producers, and adds a handler at the iterator that includes execution
tracing.
=> Move per-producer exception handling up a level

src/main/scala/sectery/producers/Config.scala, src/main/scala/sectery/producers/Time.scala, src/test/scala/sectery/producers/TimeSpec.scala
This uses `sectery.producers.Config` to check whether the user has
previously set `tz` to format responses to `@time` in their local time
zone.
Fixes #173
=> Allow users to set their local time zone

src/main/scala/sectery/Db.scala
Database connections are a closeable resource.  This closes each one
after the transaction ends in either a commit or a rollback.
=> Close each database connection at transaction end

src/main/scala/sectery/MessageQueues.scala, src/main/scala/sectery/Producer.scala, src/test/scala/sectery/producers/GrabSpec.scala
This changes `Rx` from a case class into a regular class with a manually
maintained extractor.  The extractor strips out any leading `<nick>`,
which allows matching on the clean message without losing access to the
raw message, e.g. for saving in the LAST_MESSAGE table.
This improves upon 7d4fd4fa87db17004b38c25d0b611f238a92a440
=> Move the leading nick stripper to the Rx extractor

src/main/scala/sectery/MessageQueues.scala
This removes the need for individual pattern matches to allow for
leading and trailing whitespace.
=> Trim leading and trailing whitespace for matching

src/main/scala/sectery/producers/Stock.scala, src/test/scala/sectery/producers/StockSpec.scala
This makes arguments to `@stock` optional, if a user has set a default.
=> Allow users to set default stock symbols

src/main/scala/sectery/producers/Frinkiac.scala, src/test/scala/sectery/producers/FrinkiacSpec.scala
This updates `@frinkiac` to retrieve all available subtitles for a
selected caption, since there can be a few.
=> Retrieve all subtitles for a given caption

src/main/scala/sectery/producers/LastMessage.scala, src/main/scala/sectery/producers/Substitute.scala, src/test/scala/sectery/producers/SubstituteSpec.scala
This modifies the last message logger to ignore messages that match
either of the substitution patterns `s/foo/bar/[g]`.
Fixes #70
=> Don't save substitutions as last messages

src/main/scala/sectery/Bot.scala, src/main/scala/sectery/Sectery.scala
This adds a single place to set the message delay, and configures both
the ZIO scheduler and the PircBotX infrastructure to use it.
=> Set message delay from a shared config val

src/main/scala/sectery/Producer.scala, src/main/scala/sectery/producers/Blink.scala, src/test/scala/sectery/producers/BlinkSpec.scala, src/test/scala/sectery/producers/HelpSpec.scala
This reintroduces support for blinking text via `@blink <text>`, which
just echos text wrapped in unicode character U+0006.
=> Add support for @blink

src/main/scala/sectery/producers/Ascii.scala
This adds some extra space above and below the image used to generate
`@ascii` results, so that nothing gets cut off.  Any extra remaining
space is trimmed at the end.
=> Give @ascii vertical buffers, then trim each

src/main/scala/sectery/MessageQueues.scala, src/main/scala/sectery/producers/Ascii.scala, src/main/scala/sectery/producers/Blink.scala, src/test/scala/sectery/producers/AsciiSpec.scala, src/test/scala/sectery/producers/PipeSpec.scala
Also drop the `[blink]` argument from `@ascii` in favor of piping to
`@blink`.
=> Add support for a pipe operator

modules/producers/src/main/scala/sectery/Db.scala, modules/producers/src/main/scala/sectery/Http.scala
> method `accessZIO` in object `ZIO` is deprecated since 2.0.0: use
> `environmentWithZIO`
=> Update from deprecated ZIO API

build.sbt, modules/producers/src/main/scala/sectery/producers/Tell.scala, modules/producers/src/test/scala/sectery/producers/TellSpec.scala
This adds the [`PrettyTime` library][1] for formatting dates as relative
amounts of time in the past/future, and uses it for delivering `@tell`
messages.
[1]: https://github.com/ocpsoft/prettytime
=> Format dates as "<duration> <time unit>s ago"

.github/workflows/deploy.yml, build.sbt, modules/producers/src/main/scala/sectery/Autoquote.scala, modules/producers/src/test/scala/sectery/producers/GrabSpec.scala, project/plugins.sbt
1. Update the CD workflow to target AWS Elastic Beanstalk
2. Add sbt-assembly for packaging all dependencies in a single .jar file
3. Specify the main class to allow running via `java -jar assembly.jar`
4. Use UTC-7 for the autoquote time zone
=> Migrate from Heroku to AWS Elastic Beanstalk

.github/workflows/deploy.yml
Elastic Beanstalk doesn't like concurrent deployments, and will fail a
build when more than one are run at once:
> Environment named <env name> is in an invalid state for this
> operation. Must be Ready.
This adds [Turnstyle][1] to the deployment workflow to make deployments
wait until it's safe to go.
[1]: https://github.com/softprops/turnstyle
=> Use Turnstyle to prevent concurrent runs

.github/workflows/deploy-irc.yml, .github/workflows/deploy-producers.yml
We don't need to deploy the irc module when only the producers code has
changed (and vice versa).  This splits the deployment workflow into two,
one for each module.
For more info on filter patterns, see:
<https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#patterns-to-match-file-paths>
=> Use path filters to deploy modules individually

build.sbt, modules/producers/src/main/scala/sectery/producers/Hack.scala
This reverts commit 02e87f0ed8f1ee67a5af20a4d88b044b9dbcab5b.
zio-json is still compiled against RC2, which isn't compatible with RC3:
```
java.lang.NoClassDefFoundError: zio/ZManaged
```
Once zio-json migrates to RC3 we can reapply this update.
=> Revert "Update zio from 2.0.0-RC2 to 2.0.0-RC3 (#350)"

build.sbt, modules/producers/src/test/scala/sectery/producers/ProducerSpec.scala
zio-aws and zio-json are still on RC3, so we can't update to RC4 yet.
=> Roll ZIO back from 2.0.0-RC4 to 2.0.0-RC3

build.sbt
This had been reverted by a faulty merge.
=> Update ZIO from 2.0.1 to 2.0.2

build.sbt, default.nix
📦 Updates 
* [dev.zio:zio-aws-netty](https://github.com/zio/zio-aws)
* [dev.zio:zio-aws-sqs](https://github.com/zio/zio-aws)
from `6.20.83.1` to `6.20.83.2`
📜 [GitHub Release Notes](https://github.com/zio/zio-aws/releases/tag/v6.20.83.2) - [Version Diff](https://github.com/zio/zio-aws/compare/v6.20.83.1...v6.20.83.2)
=> zio-aws: 6.20.83.1 -> 6.20.83.2

default.nix, project/build.properties
📦 Updates [org.scala-sbt:sbt](https://github.com/sbt/sbt) from `1.9.1` to `1.9.2`
📜 [GitHub Release Notes](https://github.com/sbt/sbt/releases/tag/v1.9.2) - [Version Diff](https://github.com/sbt/sbt/compare/v1.9.1...v1.9.2)
=> sbt: 1.9.1 -> 1.9.2

.scalafmt.conf, default.nix
📦 Updates [org.scalameta:scalafmt-core](https://github.com/scalameta/scalafmt) from `3.7.7` to `3.7.9`
📜 [GitHub Release Notes](https://github.com/scalameta/scalafmt/releases/tag/v3.7.9) - [Version Diff](https://github.com/scalameta/scalafmt/compare/v3.7.7...v3.7.9)
=> scalafmt-core: 3.7.7 -> 3.7.9

build.sbt, default.nix
📦 Updates 
* [dev.zio:zio-aws-netty](https://github.com/zio/zio-aws)
* [dev.zio:zio-aws-sqs](https://github.com/zio/zio-aws)
from `6.20.83.2` to `6.20.103.1`
📜 [GitHub Release Notes](https://github.com/zio/zio-aws/releases/tag/v6.20.103.1) - [Version Diff](https://github.com/zio/zio-aws/compare/v6.20.83.2...v6.20.103.1)
=> zio-aws: 6.20.83.2 -> 6.20.103.1

.scalafmt.conf, default.nix
📦 Updates [org.scalameta:scalafmt-core](https://github.com/scalameta/scalafmt) from `3.7.9` to `3.7.10`
📜 [GitHub Release Notes](https://github.com/scalameta/scalafmt/releases/tag/v3.7.10) - [Version Diff](https://github.com/scalameta/scalafmt/compare/v3.7.9...v3.7.10)
=> scalafmt-core: 3.7.9 -> 3.7.10

default.nix, project/build.properties
📦 Updates [org.scala-sbt:sbt](https://github.com/sbt/sbt) from `1.9.2` to `1.9.3`
📜 [GitHub Release Notes](https://github.com/sbt/sbt/releases/tag/v1.9.3) - [Version Diff](https://github.com/sbt/sbt/compare/v1.9.2...v1.9.3)
=> sbt: 1.9.2 -> 1.9.3

.scalafmt.conf, default.nix
📦 Updates [org.scalameta:scalafmt-core](https://github.com/scalameta/scalafmt) from `3.7.10` to `3.7.12`
📜 [GitHub Release Notes](https://github.com/scalameta/scalafmt/releases/tag/v3.7.12) - [Version Diff](https://github.com/scalameta/scalafmt/compare/v3.7.10...v3.7.12)
=> scalafmt-core: 3.7.10 -> 3.7.12

build.sbt, default.nix
📦 Updates [com.rabbitmq:amqp-client](https://github.com/rabbitmq/rabbitmq-java-client) from `5.14.2` to `5.14.3`
📜 [GitHub Release Notes](https://github.com/rabbitmq/rabbitmq-java-client/releases/tag/v5.14.3) - [Version Diff](https://github.com/rabbitmq/rabbitmq-java-client/compare/v5.14.2...v5.14.3)
=> amqp-client: 5.14.2 -> 5.14.3

build.sbt, default.nix
📦 Updates [dev.zio:zio-logging](https://github.com/zio/zio-logging) from `2.1.13` to `2.1.14`
📜 [GitHub Release Notes](https://github.com/zio/zio-logging/releases/tag/v2.1.14) - [Version Diff](https://github.com/zio/zio-logging/compare/v2.1.13...v2.1.14)
=> zio-logging: 2.1.13 -> 2.1.14

build.sbt, default.nix
📦 Updates [com.rabbitmq:amqp-client](https://github.com/rabbitmq/rabbitmq-java-client) from `5.14.3` to `5.18.0`
📜 [GitHub Release Notes](https://github.com/rabbitmq/rabbitmq-java-client/releases/tag/v5.18.0) - [Version Diff](https://github.com/rabbitmq/rabbitmq-java-client/compare/v5.14.3...v5.18.0)
=> amqp-client: 5.14.3 -> 5.18.0

default.nix, project/plugins.sbt
📦 Updates [org.scalameta:sbt-scalafmt](https://github.com/scalameta/sbt-scalafmt) from `2.5.0` to `2.5.2`
📜 [GitHub Release Notes](https://github.com/scalameta/sbt-scalafmt/releases/tag/v2.5.2) - [Version Diff](https://github.com/scalameta/sbt-scalafmt/compare/v2.5.0...v2.5.2)
=> sbt-scalafmt: 2.5.0 -> 2.5.2

.scalafmt.conf, default.nix
📦 Updates [org.scalameta:scalafmt-core](https://github.com/scalameta/scalafmt) from `3.7.12` to `3.7.14`
📜 [GitHub Release Notes](https://github.com/scalameta/scalafmt/releases/tag/v3.7.14) - [Version Diff](https://github.com/scalameta/scalafmt/compare/v3.7.12...v3.7.14)
=> scalafmt-core: 3.7.12 -> 3.7.14

build.sbt, default.nix
📦 Updates [org.scala-lang:scala3-library](https://github.com/lampepfl/dotty) from `3.3.0` to `3.3.1`
📜 [GitHub Release Notes](https://github.com/lampepfl/dotty/releases/tag/3.3.1) - [Version Diff](https://github.com/lampepfl/dotty/compare/3.3.0...3.3.1) - [Version Diff](https://github.com/lampepfl/dotty/compare/release-3.3.0...release-3.3.1)
=> scala3-library: 3.3.0 -> 3.3.1

default.nix, project/build.properties
📦 Updates [org.scala-sbt:sbt](https://github.com/sbt/sbt) from `1.9.4` to `1.9.6`
📜 [GitHub Release Notes](https://github.com/sbt/sbt/releases/tag/v1.9.6) - [Version Diff](https://github.com/sbt/sbt/compare/v1.9.4...v1.9.6)
=> sbt: 1.9.4 -> 1.9.6

default.nix, project/plugins.sbt
📦 Updates [com.eed3si9n:sbt-assembly](https://github.com/sbt/sbt-assembly) from `2.1.1` to `2.1.3`
📜 [GitHub Release Notes](https://github.com/sbt/sbt-assembly/releases/tag/v2.1.3) - [Version Diff](https://github.com/sbt/sbt-assembly/compare/v2.1.1...v2.1.3)
=> sbt-assembly: 2.1.1 -> 2.1.3

build.sbt, default.nix
📦 Updates [com.rabbitmq:amqp-client](https://github.com/rabbitmq/rabbitmq-java-client) from `5.18.0` to `5.19.0`
📜 [GitHub Release Notes](https://github.com/rabbitmq/rabbitmq-java-client/releases/tag/v5.19.0) - [Version Diff](https://github.com/rabbitmq/rabbitmq-java-client/compare/v5.18.0...v5.19.0)
=> amqp-client: 5.18.0 -> 5.19.0

build.sbt, default.nix
📦 Updates [org.jsoup:jsoup](https://github.com/jhy/jsoup) from `1.16.1` to `1.16.2`
=> jsoup: 1.16.1 -> 1.16.2

default.nix, project/plugins.sbt
📦 Updates [com.eed3si9n:sbt-assembly](https://github.com/sbt/sbt-assembly) from `2.1.3` to `2.1.4`
📜 [GitHub Release Notes](https://github.com/sbt/sbt-assembly/releases/tag/v2.1.4) - [Version Diff](https://github.com/sbt/sbt-assembly/compare/v2.1.3...v2.1.4)
=> sbt-assembly: 2.1.3 -> 2.1.4

build.sbt, default.nix
📦 Updates [com.rabbitmq:amqp-client](https://github.com/rabbitmq/rabbitmq-java-client) from `5.19.0` to `5.20.0`
📜 [GitHub Release Notes](https://github.com/rabbitmq/rabbitmq-java-client/releases/tag/v5.20.0) - [Version Diff](https://github.com/rabbitmq/rabbitmq-java-client/compare/v5.19.0...v5.20.0)
=> amqp-client: 5.19.0 -> 5.20.0

default.nix, project/build.properties
📦 Updates [org.scala-sbt:sbt](https://github.com/sbt/sbt) from `1.9.6` to `1.9.7`
📜 [GitHub Release Notes](https://github.com/sbt/sbt/releases/tag/v1.9.7) - [Version Diff](https://github.com/sbt/sbt/compare/v1.9.6...v1.9.7)
=> sbt: 1.9.6 -> 1.9.7

.scalafmt.conf, default.nix
📦 Updates [org.scalameta:scalafmt-core](https://github.com/scalameta/scalafmt) from `3.7.14` to `3.7.15`
📜 [GitHub Release Notes](https://github.com/scalameta/scalafmt/releases/tag/v3.7.15) - [Version Diff](https://github.com/scalameta/scalafmt/compare/v3.7.14...v3.7.15)
=> scalafmt-core: 3.7.14 -> 3.7.15

build.sbt, default.nix
📦 Updates [dev.zio:zio-logging](https://github.com/zio/zio-logging) from `2.1.14` to `2.1.15`
📜 [GitHub Release Notes](https://github.com/zio/zio-logging/releases/tag/v2.1.15) - [Version Diff](https://github.com/zio/zio-logging/compare/v2.1.14...v2.1.15)
=> zio-logging: 2.1.14 -> 2.1.15

build.sbt, default.nix
📦 Updates [org.mariadb.jdbc:mariadb-java-client](https://github.com/mariadb-corporation/mariadb-connector-j) from `3.2.0` to `3.3.0`
📜 [GitHub Release Notes](https://github.com/mariadb-corporation/mariadb-connector-j/releases/tag/3.3.0) - [Changelog](https://github.com/mariadb-corporation/mariadb-connector-j/blob/master/CHANGELOG.md) - [Version Diff](https://github.com/mariadb-corporation/mariadb-connector-j/compare/3.2.0...3.3.0)
=> mariadb-java-client: 3.2.0 -> 3.3.0

.scalafmt.conf, default.nix
📦 Updates [org.scalameta:scalafmt-core](https://github.com/scalameta/scalafmt) from `3.7.15` to `3.7.17`
📜 [GitHub Release Notes](https://github.com/scalameta/scalafmt/releases/tag/v3.7.17) - [Version Diff](https://github.com/scalameta/scalafmt/compare/v3.7.15...v3.7.17)
=> scalafmt-core: 3.7.15 -> 3.7.17

default.nix, project/plugins.sbt
📦 Updates [com.eed3si9n:sbt-assembly](https://github.com/sbt/sbt-assembly) from `2.1.4` to `2.1.5`
📜 [GitHub Release Notes](https://github.com/sbt/sbt-assembly/releases/tag/v2.1.5) - [Version Diff](https://github.com/sbt/sbt-assembly/compare/v2.1.4...v2.1.5)
=> sbt-assembly: 2.1.4 -> 2.1.5

build.sbt, default.nix
📦 Updates [dev.zio:zio-logging](https://github.com/zio/zio-logging) from `2.1.15` to `2.1.16`
📜 [GitHub Release Notes](https://github.com/zio/zio-logging/releases/tag/v2.1.16) - [Version Diff](https://github.com/zio/zio-logging/compare/v2.1.15...v2.1.16)
=> zio-logging: 2.1.15 -> 2.1.16

build.sbt, default.nix
📦 Updates [org.jsoup:jsoup](https://github.com/jhy/jsoup) from `1.16.2` to `1.17.1`
📜 [Changelog](https://github.com/jhy/jsoup/blob/master/CHANGES.md)
=> jsoup: 1.16.2 -> 1.17.1

default.nix, project/build.properties
📦 Updates [org.scala-sbt:sbt](https://github.com/sbt/sbt) from `1.9.7` to `1.9.8`
📜 [GitHub Release Notes](https://github.com/sbt/sbt/releases/tag/v1.9.8) - [Version Diff](https://github.com/sbt/sbt/compare/v1.9.7...v1.9.8)
=> sbt: 1.9.7 -> 1.9.8

build.sbt, default.nix
📦 Updates [org.jsoup:jsoup](https://github.com/jhy/jsoup) from `1.17.1` to `1.17.2`
📜 [Changelog](https://github.com/jhy/jsoup/blob/master/CHANGES.md)
=> jsoup: 1.17.1 -> 1.17.2

build.sbt, default.nix
📦 Updates [dev.zio:zio-logging](https://github.com/zio/zio-logging) from `2.1.16` to `2.1.17`
📜 [GitHub Release Notes](https://github.com/zio/zio-logging/releases/tag/v2.1.17) - [Version Diff](https://github.com/zio/zio-logging/compare/v2.1.16...v2.1.17)
=> zio-logging: 2.1.16 -> 2.1.17

build.sbt, default.nix
📦 Updates [dev.zio:zio-logging](https://github.com/zio/zio-logging) from `2.1.17` to `2.2.0`
📜 [GitHub Release Notes](https://github.com/zio/zio-logging/releases/tag/v2.2.0) - [Version Diff](https://github.com/zio/zio-logging/compare/v2.1.17...v2.2.0)
=> zio-logging: 2.1.17 -> 2.2.0

build.sbt, default.nix
📦 Updates [dev.zio:zio-logging](https://github.com/zio/zio-logging) from `2.2.0` to `2.2.1`
📜 [GitHub Release Notes](https://github.com/zio/zio-logging/releases/tag/v2.2.1) - [Version Diff](https://github.com/zio/zio-logging/compare/v2.2.0...v2.2.1)
=> zio-logging: 2.2.0 -> 2.2.1

build.sbt, default.nix
📦 Updates [dev.zio:zio-logging](https://github.com/zio/zio-logging) from `2.2.1` to `2.2.2`
📜 [GitHub Release Notes](https://github.com/zio/zio-logging/releases/tag/v2.2.2) - [Version Diff](https://github.com/zio/zio-logging/compare/v2.2.1...v2.2.2)
=> zio-logging: 2.2.1 -> 2.2.2

default.nix, project/build.properties
📦 Updates [org.scala-sbt:sbt](https://github.com/sbt/sbt) from `1.9.8` to `1.9.9`
📜 [GitHub Release Notes](https://github.com/sbt/sbt/releases/tag/v1.9.9) - [Version Diff](https://github.com/sbt/sbt/compare/v1.9.8...v1.9.9)
=> sbt: 1.9.8 -> 1.9.9

build.sbt, default.nix
📦 Updates [org.scala-lang:scala3-library](https://github.com/lampepfl/dotty) from `3.3.1` to `3.3.3`
📜 [GitHub Release Notes](https://github.com/lampepfl/dotty/releases/tag/3.3.3) - [Version Diff](https://github.com/lampepfl/dotty/compare/3.3.1...3.3.3) - [Version Diff](https://github.com/lampepfl/dotty/compare/release-3.3.1...release-3.3.3)
=> scala3-library: 3.3.1 -> 3.3.3

default.nix, project/plugins.sbt
📦 Updates [com.eed3si9n:sbt-assembly](https://github.com/sbt/sbt-assembly) from `2.1.5` to `2.2.0`
📜 [GitHub Release Notes](https://github.com/sbt/sbt-assembly/releases/tag/v2.2.0) - [Version Diff](https://github.com/sbt/sbt-assembly/compare/v2.1.5...v2.2.0)
=> sbt-assembly: 2.1.5 -> 2.2.0

.scalafmt.conf, default.nix
📦 Updates [org.scalameta:scalafmt-core](https://github.com/scalameta/scalafmt) from `3.8.0` to `3.8.1`
📜 [GitHub Release Notes](https://github.com/scalameta/scalafmt/releases/tag/v3.8.1) - [Version Diff](https://github.com/scalameta/scalafmt/compare/v3.8.0...v3.8.1)
=> scalafmt-core: 3.8.0 -> 3.8.1

default.nix, project/plugins.sbt
📦 Updates [com.github.sbt:sbt-native-packager](https://github.com/sbt/sbt-native-packager) from `1.9.16` to `1.10.0`
📜 [GitHub Release Notes](https://github.com/sbt/sbt-native-packager/releases/tag/v1.10.0) - [Changelog](https://github.com/sbt/sbt-native-packager/blob/master/CHANGELOG.md) - [Version Diff](https://github.com/sbt/sbt-native-packager/compare/v1.9.16...v1.10.0)
=> sbt-native-packager: 1.9.16 -> 1.10.0

build.sbt, default.nix
📦 Updates [com.rabbitmq:amqp-client](https://github.com/rabbitmq/rabbitmq-java-client) from `5.20.0` to `5.21.0`
📜 [GitHub Release Notes](https://github.com/rabbitmq/rabbitmq-java-client/releases/tag/v5.21.0) - [Version Diff](https://github.com/rabbitmq/rabbitmq-java-client/compare/v5.20.0...v5.21.0)
=> amqp-client: 5.20.0 -> 5.21.0

build.sbt, default.nix
📦 Updates [dev.zio:zio-logging](https://github.com/zio/zio-logging) from `2.2.2` to `2.2.4`
📜 [GitHub Release Notes](https://github.com/zio/zio-logging/releases/tag/v2.2.4) - [Version Diff](https://github.com/zio/zio-logging/compare/v2.2.2...v2.2.4)
=> zio-logging: 2.2.2 -> 2.2.4

build.sbt, default.nix
📦 Updates [org.mariadb.jdbc:mariadb-java-client](https://github.com/mariadb-corporation/mariadb-connector-j) from `3.3.3` to `3.4.0`
📜 [GitHub Release Notes](https://github.com/mariadb-corporation/mariadb-connector-j/releases/tag/3.4.0) - [Changelog](https://github.com/mariadb-corporation/mariadb-connector-j/blob/master/CHANGELOG.md) - [Version Diff](https://github.com/mariadb-corporation/mariadb-connector-j/compare/3.3.3...3.4.0)
=> mariadb-java-client: 3.3.3 -> 3.4.0

build.sbt, default.nix
📦 Updates org.ocpsoft.prettytime:prettytime from `5.0.7.Final` to `5.0.8.Final`
=> prettytime: 5.0.7.Final -> 5.0.8.Final

default.nix, project/build.properties
📦 Updates [org.scala-sbt:sbt](https://github.com/sbt/sbt) from `1.9.9` to `1.10.0`
📜 [GitHub Release Notes](https://github.com/sbt/sbt/releases/tag/v1.10.0) - [Version Diff](https://github.com/sbt/sbt/compare/v1.9.9...v1.10.0)
=> sbt: 1.9.9 -> 1.10.0

build.sbt, default.nix
📦 Updates [dev.zio:zio-logging](https://github.com/zio/zio-logging) from `2.2.4` to `2.3.0`
📜 [GitHub Release Notes](https://github.com/zio/zio-logging/releases/tag/v2.3.0) - [Version Diff](https://github.com/zio/zio-logging/compare/v2.2.4...v2.3.0)
=> zio-logging: 2.2.4 -> 2.3.0

build.sbt, default.nix
📦 Updates 
* [org.scalameta:munit](https://github.com/scalameta/munit)
* [org.scalameta:munit-scalacheck](https://github.com/scalameta/munit-scalacheck)
from `0.7.29` to `1.0.0` ⚠
📜 [GitHub Release Notes](https://github.com/scalameta/munit/releases/tag/v1.0.0) - [Version Diff](https://github.com/scalameta/munit/compare/v0.7.29...v1.0.0)
=> munit: 0.7.29 -> 1.0.0

build.sbt, default.nix
📦 Updates [org.glassfish.tyrus.bundles:tyrus-standalone-client](https://github.com/eclipse-ee4j/tyrus) from `1.19` to `1.21`
📜 [GitHub Release Notes](https://github.com/eclipse-ee4j/tyrus/releases/tag/1.21) - [Version Diff](https://github.com/eclipse-ee4j/tyrus/compare/1.19...1.21)
=> tyrus-standalone-client: 1.19 -> 1.21

build.sbt, default.nix
📦 Updates 
* [com.dimafeng:testcontainers-scala-mariadb](https://github.com/testcontainers/testcontainers-scala)
* [com.dimafeng:testcontainers-scala-rabbitmq](https://github.com/testcontainers/testcontainers-scala)
from `0.41.3` to `0.41.4`
📜 [GitHub Release Notes](https://github.com/testcontainers/testcontainers-scala/releases/tag/v0.41.4) - [Version Diff](https://github.com/testcontainers/testcontainers-scala/compare/v0.41.3...v0.41.4)
=> testcontainers-scala-mariadb, ...: 0.41.3 -> 0.41.4

build.sbt, default.nix
📦 Updates [com.slack.api:bolt-socket-mode](https://github.com/slackapi/java-slack-sdk) from `1.39.3` to `1.40.1`
📜 [GitHub Release Notes](https://github.com/slackapi/java-slack-sdk/releases/tag/v1.40.1) - [Version Diff](https://github.com/slackapi/java-slack-sdk/compare/v1.39.3...v1.40.1)
=> bolt-socket-mode: 1.39.3 -> 1.40.1

.scalafmt.conf, build.sbt, default.nix
📦 Updates [org.scalameta:scalafmt-core](https://github.com/scalameta/scalafmt) from `3.8.1` to `3.8.2`
📜 [GitHub Release Notes](https://github.com/scalameta/scalafmt/releases/tag/v3.8.2) - [Version Diff](https://github.com/scalameta/scalafmt/compare/v3.8.1...v3.8.2)
=> scalafmt-core: 3.8.1 -> 3.8.2

build.sbt, default.nix
📦 Updates [com.slack.api:bolt-socket-mode](https://github.com/slackapi/java-slack-sdk) from `1.40.1` to `1.40.2`
📜 [GitHub Release Notes](https://github.com/slackapi/java-slack-sdk/releases/tag/v1.40.2) - [Version Diff](https://github.com/slackapi/java-slack-sdk/compare/v1.40.1...v1.40.2)
=> bolt-socket-mode: 1.40.1 -> 1.40.2

build.sbt, default.nix
📦 Updates [com.slack.api:bolt-socket-mode](https://github.com/slackapi/java-slack-sdk) from `1.40.2` to `1.40.3`
📜 [GitHub Release Notes](https://github.com/slackapi/java-slack-sdk/releases/tag/v1.40.3) - [Version Diff](https://github.com/slackapi/java-slack-sdk/compare/v1.40.2...v1.40.3)
=> bolt-socket-mode: 1.40.2 -> 1.40.3

build.sbt, default.nix
📦 Updates [org.mariadb.jdbc:mariadb-java-client](https://github.com/mariadb-corporation/mariadb-connector-j) from `3.4.0` to `3.4.1`
📜 [GitHub Release Notes](https://github.com/mariadb-corporation/mariadb-connector-j/releases/tag/3.4.1) - [Changelog](https://github.com/mariadb-corporation/mariadb-connector-j/blob/master/CHANGELOG.md) - [Version Diff](https://github.com/mariadb-corporation/mariadb-connector-j/compare/3.4.0...3.4.1)
=> mariadb-java-client: 3.4.0 -> 3.4.1

build.sbt, default.nix, project/build.properties
📦 Updates [org.scala-sbt:sbt](https://github.com/sbt/sbt) from `1.10.0` to `1.10.1`
📜 [GitHub Release Notes](https://github.com/sbt/sbt/releases/tag/v1.10.1) - [Version Diff](https://github.com/sbt/sbt/compare/v1.10.0...v1.10.1)
=> sbt: 1.10.0 -> 1.10.1

.scalafmt.conf, default.nix
📦 Updates [org.scalameta:scalafmt-core](https://github.com/scalameta/scalafmt) from `3.8.2` to `3.8.3`
📜 [GitHub Release Notes](https://github.com/scalameta/scalafmt/releases/tag/v3.8.3) - [Version Diff](https://github.com/scalameta/scalafmt/compare/v3.8.2...v3.8.3)
=> scalafmt-core: 3.8.2 -> 3.8.3

default.nix, project/plugins.sbt
📦 Updates [com.github.sbt:sbt-native-packager](https://github.com/sbt/sbt-native-packager) from `1.10.0` to `1.10.4`
📜 [GitHub Release Notes](https://github.com/sbt/sbt-native-packager/releases/tag/v1.10.4) - [Changelog](https://github.com/sbt/sbt-native-packager/blob/master/CHANGELOG.md) - [Version Diff](https://github.com/sbt/sbt-native-packager/compare/v1.10.0...v1.10.4)
=> sbt-native-packager: 1.10.0 -> 1.10.4

build.sbt, default.nix
📦 Updates [org.glassfish.tyrus.bundles:tyrus-standalone-client](https://github.com/eclipse-ee4j/tyrus) from `2.1.5` to `2.2.0`
📜 [GitHub Release Notes](https://github.com/eclipse-ee4j/tyrus/releases/tag/2.2.0) - [Version Diff](https://github.com/eclipse-ee4j/tyrus/compare/2.1.5...2.2.0)
=> tyrus-standalone-client: 2.1.5 -> 2.2.0

build.sbt, default.nix
📦 Updates [com.slack.api:bolt-socket-mode](https://github.com/slackapi/java-slack-sdk) from `1.40.3` to `1.42.0`
📜 [GitHub Release Notes](https://github.com/slackapi/java-slack-sdk/releases/tag/v1.42.0) - [Version Diff](https://github.com/slackapi/java-slack-sdk/compare/v1.40.3...v1.42.0)
=> bolt-socket-mode: 1.40.3 -> 1.42.0

build.sbt, default.nix
📦 Updates [dev.zio:zio](https://github.com/zio/zio) from `2.1.6` to `2.1.8`
📜 [GitHub Release Notes](https://github.com/zio/zio/releases/tag/v2.1.8) - [Version Diff](https://github.com/zio/zio/compare/v2.1.6...v2.1.8)
=> zio: 2.1.6 -> 2.1.8

build.sbt, default.nix
📦 Updates [dev.zio:zio-logging](https://github.com/zio/zio-logging) from `2.3.0` to `2.3.1`
📜 [GitHub Release Notes](https://github.com/zio/zio-logging/releases/tag/v2.3.1) - [Version Diff](https://github.com/zio/zio-logging/compare/v2.3.0...v2.3.1)
=> zio-logging: 2.3.0 -> 2.3.1

build.sbt, default.nix
📦 Updates [org.scala-lang:scala3-library](https://github.com/scala/scala3) from `3.4.2` to `3.4.3`
📜 [GitHub Release Notes](https://github.com/scala/scala3/releases/tag/3.4.3) - [Version Diff](https://github.com/scala/scala3/compare/3.4.2...3.4.3) - [Version Diff](https://github.com/scala/scala3/compare/release-3.4.2...release-3.4.3)
=> scala3-library: 3.4.2 -> 3.4.3

build.sbt, default.nix
📦 Updates [ch.qos.logback:logback-classic](https://github.com/qos-ch/logback) from `1.5.6` to `1.5.7`
=> logback-classic: 1.5.6 -> 1.5.7

build.sbt, default.nix, modules/5-slack/src/main/scala/slack/Slack.scala, src/test/scala/Main.scala
📦 Updates [org.scala-lang:scala3-library](https://github.com/scala/scala3) from `3.4.3` to `3.5.0`
📜 [GitHub Release Notes](https://github.com/scala/scala3/releases/tag/3.5.0) - [Version Diff](https://github.com/scala/scala3/compare/3.4.3...3.5.0) - [Version Diff](https://github.com/scala/scala3/compare/release-3.4.3...release-3.5.0)
=> scala3-library: 3.4.3 -> 3.5.0

build.sbt, default.nix
📦 Updates [ch.qos.logback:logback-classic](https://github.com/qos-ch/logback) from `1.5.7` to `1.5.8`
=> logback-classic: 1.5.7 -> 1.5.8

build.sbt, default.nix
📦 Updates [com.slack.api:bolt-socket-mode](https://github.com/slackapi/java-slack-sdk) from `1.42.0` to `1.42.1`
📜 [GitHub Release Notes](https://github.com/slackapi/java-slack-sdk/releases/tag/v1.42.1) - [Version Diff](https://github.com/slackapi/java-slack-sdk/compare/v1.42.0...v1.42.1)
=> bolt-socket-mode: 1.42.0 -> 1.42.1

build.sbt, default.nix
📦 Updates [org.scalameta:munit](https://github.com/scalameta/munit) from `1.0.1` to `1.0.2`
📜 [GitHub Release Notes](https://github.com/scalameta/munit/releases/tag/v1.0.2) - [Version Diff](https://github.com/scalameta/munit/compare/v1.0.1...v1.0.2)
=> munit: 1.0.1 -> 1.0.2

build.sbt, default.nix
📦 Updates [ch.qos.logback:logback-classic](https://github.com/qos-ch/logback) from `1.5.8` to `1.5.9`
=> logback-classic: 1.5.8 -> 1.5.9

build.sbt, default.nix
📦 Updates [dev.zio:zio](https://github.com/zio/zio) from `2.1.9` to `2.1.11`
📜 [GitHub Release Notes](https://github.com/zio/zio/releases/tag/v2.1.11) - [Version Diff](https://github.com/zio/zio/compare/v2.1.9...v2.1.11)
=> zio: 2.1.9 -> 2.1.11

build.sbt, default.nix
📦 Updates [org.scala-lang:scala3-library](https://github.com/scala/scala3) from `3.5.0` to `3.5.1`
📜 [GitHub Release Notes](https://github.com/scala/scala3/releases/tag/3.5.1) - [Version Diff](https://github.com/scala/scala3/compare/3.5.0...3.5.1)
=> scala3-library: 3.5.0 -> 3.5.1

build.sbt, default.nix
📦 Updates [ch.qos.logback:logback-classic](https://github.com/qos-ch/logback) from `1.5.9` to `1.5.10`
=> logback-classic: 1.5.9 -> 1.5.10

build.sbt, default.nix
Without this, attempting to use a local socket connection (e.g. `jdbc:mariadb://localhost:3306/<db>?localSocket=/var/run/mysqld/mysqld.sock`) fails with:
```
connect: The address can't be null
at java.base/java.net.Socket.connect(Socket.java:605)
```
=> Add JNA library to support local socket to MariaDB
