config.json.example
lib/plugins/weatherunderground.js
test/sectry_test.js

Added the weatherunderground plugin. Just need to supply the real API key in the config.json file.

added weatherunderground plugin

---

.gitignore
config.example.json
lib/main.js
lib/plugins/tell.js
package.json
test/sectry_test.js

This is a first attempt at addressing issue #17.

make changes to nconf

---

.gitignore
.travis.yml
lib/ascii-art.js
lib/client.js
lib/http-client.js
lib/listeners/message/note.js
lib/listeners/message/tell.js
lib/listeners/pm/setup.js
lib/scala.js
lib/sectery.js
lib/utilities.js
package.json
test/sectry_test.js

**TODO: Convert the rest of the missing tests.**

Get rid of mocks; test live on IRC

---

lib/listeners/message/http-title.js

/* returns: 'foo</title>bar<title>baz' */
/<title>(.+)<\/title>/.exec('<title>foo</title>bar<title>baz</title>')[1]
/* returns: 'foo' */
/<title>(.+?)<\/title>/.exec('<title>foo</title>bar<title>baz</title>')[1]

Use lazy regex for parsing html <title/>

---

lib/listeners/message/auto-reply.js
test/sectry_test.js

Added autoreply feature to dynamically add replies

---

lib/listeners/message/auto-reply.js

Don't return messages on the first iteration of the loop.

Fix no reply issue

---

lib/listeners/message/weather.js
package.json
test/sectry_test.js

Strip ansi esc chars (blink) from @weather output

---

lib/listeners/message/points.js
test/sectry_test.js

Don't allow folk to self-add (or self-remove) points

---

.github/workflows/scala.yml
build.sbt
project/build.properties
src/main/scala/Main.scala
src/test/scala/Test1.scala

This was generated from [scala/scala3.g8][1]:
```
$ sbt new scala/scala3.g8
```
[1]: https://github.com/scala/scala3.g8

Bootstrap a skeleton Scala 3 project

---

build.sbt
src/main/scala/Main.scala
src/test/scala/HelloWorldSpec.scala
src/test/scala/Test1.scala

This is based on the example in [Use Cases/Testing][1] in the ZIO docs.
[1]: https://zio.dev/docs/usecases/usecases_testing

Add zio, zio-test, and a sample test

---

README.md
build.sbt
src/main/scala/sectery/Sectery.scala

This uses PircBotX to connect to an IRC server, and responds to `@ping`
messages with `pong` responses.

Add an imperative IRC echo bot

---

build.sbt

This lets us see what's going on behind the scenes with PircBotX.
For details, see http://www.slf4j.org/manual.html#projectDep

Add logback-classic for basic logging support

---

README.md

This was a copy/paste error from an unrelated project.

Drop unrelated badge

---

src/test/scala/sectery/MessageQueuesSpec.scala

This lets the user run tests with the live `Http` service by setting the
`TEST_HTTP_LIVE` environment variable to `true`.

Add a way to test with a live HTTP service

---

src/main/scala/sectery/Http.scala

This exposes the unsafe HTTP request function for easier testing.

Extract underlying HTTP request function

---

src/main/scala/sectery/producers/Substitute.scala

respond to `s/<pattern>/<replacement/` commands.

Substitute

---

src/main/scala/sectery/producers/Substitute.scala
src/test/scala/sectery/producers/Substitute.scala

This drops the in-memory "last message" log and puts it in the
`LAST_MESSAGE` database table instead so that it will persist between
restarts.

Use the database for message substitution

---

build.sbt

This keeps up with the latest release of ZIO.  See the release notes at
https://github.com/zio/zio/releases/tag/v1.0.9

Upgrade to ZIO 1.0.9

---

.github/workflows/scala.yml
.scalafmt.conf
project/plugins.sbt
src/main/scala/sectery/Bot.scala
src/main/scala/sectery/Finnhub.scala
src/main/scala/sectery/Http.scala
src/main/scala/sectery/MessageQueues.scala
src/main/scala/sectery/Producer.scala
src/main/scala/sectery/Sectery.scala
src/main/scala/sectery/producers/Btc.scala
src/main/scala/sectery/producers/Count.scala
src/main/scala/sectery/producers/Eval.scala
src/main/scala/sectery/producers/Html.scala
src/main/scala/sectery/producers/Stock.scala
src/main/scala/sectery/producers/Substitute.scala
src/main/scala/sectery/producers/Time.scala
src/main/scala/sectery/producers/Weather.scala
src/test/scala/sectery/MessageLogger.scala
src/test/scala/sectery/TestHttp.scala
src/test/scala/sectery/producers/BtcSpec.scala
src/test/scala/sectery/producers/CountSpec.scala
src/test/scala/sectery/producers/EvalSpec.scala
src/test/scala/sectery/producers/HelpSpec.scala
src/test/scala/sectery/producers/HtmlSpec.scala
src/test/scala/sectery/producers/PingSpec.scala
src/test/scala/sectery/producers/StockSpec.scala
src/test/scala/sectery/producers/SubstituteSpec.scala
src/test/scala/sectery/producers/TimeSpec.scala
src/test/scala/sectery/producers/WeatherSpec.scala
src/test/scala/zio/Inject.scala

This adds sbt-scalafmt, configured for Scala 3, and a CI step to check
whether sources have been formatted.  This also applies formatting to
all sources, so that the CI check will pass.

Add sbt-scalafmt

---

src/main/scala/sectery/Finnhub.scala

This replaces the not-so-great regex-based JSON parser with Json4s.

Use Json4s to parse Finnhub response

---

src/main/scala/sectery/Db.scala

Since we don't need `Db.live` at all outside of production, this makes
the whole thing lazy, and undoes the awkward lazy block used to create
its database connection.

Make Db.live lazy, rather than Db.live.conn

---

CONTRIBUTING.md
README.md

This separates user documentation and developer documentation into
README.md and CONTRIBUTING.md for clarity and discoverability.

Fork developer docs from user docs

---

CONTRIBUTING.md

This adds a three-step list for how to introduce a new message producer.
This also adds a note about using SQLite in testing.

Break out instructions for new producers

---

src/main/scala/sectery/Sectery.scala

Sectery can exit if an unhandled exception is thrown, e.g. by the
underlying IRC library.  In these cases, there's nothing to do but try
again.

Re-run Sectery if it exits

---

src/main/scala/sectery/producers/Html.scala

Open Graph or else Twitter or else plain HTML.

Reprioritize HTML title/description extraction

---

src/main/scala/sectery/producers/Tell.scala

Postgres does not approve of these.

Drop backticks in column names

---

src/main/scala/sectery/Producer.scala
src/main/scala/sectery/producers/Grab.scala
src/main/scala/sectery/producers/LastMessage.scala
src/main/scala/sectery/producers/Substitute.scala
src/test/scala/sectery/producers/GrabSpec.scala
src/test/scala/sectery/producers/HelpSpec.scala

Add support for @grab/@quote

---

src/main/scala/sectery/Db.scala

This modifies the way individual database effects are run to begin a
transaction beforehand, then either commit or rollback afterward
depending on whether any exceptions are thrown.
This fixes a consistency issue where a `DELETE` immediately followed by
an `INSERT` would throw a primary key constraint exception.

Enable per-query db transactions

---

src/main/scala/sectery/Sectery.scala

For (hopefully) better asyncronicity.

Fork the blocking `startBot()` effect

---

src/main/scala/sectery/Producer.scala
src/main/scala/sectery/producers/Config.scala
src/test/scala/sectery/producers/ConfigSpec.scala
src/test/scala/sectery/producers/HelpSpec.scala

This will be used for things like allowing users to set their local time
zone (#173).

Add @get and @set for per-nick configuration

---

build.sbt
src/main/scala/sectery/Finnhub.scala
src/main/scala/sectery/Producer.scala
src/main/scala/sectery/producers/Btc.scala
src/main/scala/sectery/producers/Frinkiac.scala
src/main/scala/sectery/producers/Weather.scala
src/test/resources/com/frinkiac/api/caption?e=S04E16&t=166465
src/test/resources/com/frinkiac/api/search?q=i+got+to+think+of+a+lie+fast
src/test/scala/sectery/producers/FrinkiacSpec.scala
src/test/scala/sectery/producers/HelpSpec.scala

This adds support for `@frinkiac <quote>`, which searches the Frinkiac
API and returns the first quote found.

Add support for looking up quotes on Frinkiac

---

src/main/scala/sectery/producers/Substitute.scala
src/test/scala/sectery/producers/SubstituteSpec.scala

The `s/foo/bar/` producer currently replaces all instances of `foo` with
`bar`.  This adds an optional trailing `g` to opt into this behavior,
and changes the default behavior to replace only the first match.

Add optional /g for substituting one vs all

---

src/main/scala/sectery/producers/Html.scala
src/test/scala/sectery/producers/HtmlSpec.scala

Squash title and description into a single message

---

src/main/scala/sectery/Producer.scala
src/main/scala/sectery/producers/Ascii.scala
src/test/scala/sectery/producers/AsciiSpec.scala
src/test/scala/sectery/producers/HelpSpec.scala

This reintroduces support for ASCII art inspired text.

Add support for @ascii

---

src/main/scala/sectery/Producer.scala
src/main/scala/sectery/producers/Morse.scala
src/test/scala/sectery/producers/HelpSpec.scala
src/test/scala/sectery/producers/MorseSpec.scala

This adds Morse a code codec:
* `@morse encode foo` produces `..-. --- ---`
* `@morse decode ..-. --- ---` produces `FOO`

Add support for @morse

---

README.md
build.sbt
modules/producers/src/main/scala/sectery/Db.scala
modules/producers/src/main/scala/sectery/producers/Config.scala

This lets us use RDS under the AWS Free Tier.

Switch from PostgreSQL to MySQL

---

build.sbt
modules/producers/src/main/scala/sectery/producers/Count.scala
modules/producers/src/main/scala/sectery/producers/Grab.scala
modules/producers/src/main/scala/sectery/producers/Hack.scala
modules/producers/src/main/scala/sectery/producers/LastMessage.scala
modules/producers/src/test/scala/sectery/TestDb.scala

* Switch from SQLite to H2 configured for MySQL mode
* Convert leftover PostgreSQL syntax to MySQL

Complete switch from PostgreSQL to MySQL

---

modules/irc/src/main/scala/sectery/irc/Bot.scala
modules/producers/src/main/scala/sectery/Producer.scala

PircBotX still enforces throttling, so this change won't lead to rate
limiting.
Fixes #342

Remove .throttleEnforce, which drops messages

---

build.sbt
default.nix

ZIO 2.0.15 also depends on Scala 3.3.0.

zio: 2.0.14 -> 2.0.15

---

build.sbt
default.nix
modules/producers/src/main/scala/sectery/Db.scala

This allows connection over a local Unix socket.

Switch from MySQL connector to MariaDB client

---

build.sbt
default.nix

📦 Updates 
from `2.0.15` to `2.0.16`
📜 [GitHub Release Notes](https://github.com/zio/zio/releases/tag/v2.0.16) - [Version Diff](https://github.com/zio/zio/compare/v2.0.15...v2.0.16)

zio: 2.0.15 -> 2.0.16

---

build.sbt
default.nix

📦 Updates [dev.zio:zio-json](https://github.com/zio/zio-json) from `0.6.0` to `0.6.1`
📜 [GitHub Release Notes](https://github.com/zio/zio-json/releases/tag/v0.6.1) - [Version Diff](https://github.com/zio/zio-json/compare/v0.6.0...v0.6.1)

zio-json: 0.6.0 -> 0.6.1

---

default.nix
project/build.properties

📦 Updates [org.scala-sbt:sbt](https://github.com/sbt/sbt) from `1.9.3` to `1.9.4`
📜 [GitHub Release Notes](https://github.com/sbt/sbt/releases/tag/v1.9.4) - [Version Diff](https://github.com/sbt/sbt/compare/v1.9.3...v1.9.4)

sbt: 1.9.3 -> 1.9.4

---

build.sbt
default.nix

📦 Updates [com.h2database:h2](https://github.com/h2database/h2database) from `2.2.220` to `2.2.222`

h2: 2.2.220 -> 2.2.222

---

build.sbt
default.nix

📦 Updates [dev.zio:zio-json](https://github.com/zio/zio-json) from `0.6.1` to `0.6.2`
📜 [GitHub Release Notes](https://github.com/zio/zio-json/releases/tag/v0.6.2) - [Version Diff](https://github.com/zio/zio-json/compare/v0.6.1...v0.6.2)

zio-json: 0.6.1 -> 0.6.2

---

build.sbt
default.nix

📦 Updates 
from `2.0.16` to `2.0.17`
📜 [GitHub Release Notes](https://github.com/zio/zio/releases/tag/v2.0.17) - [Version Diff](https://github.com/zio/zio/compare/v2.0.16...v2.0.17)

zio: 2.0.16 -> 2.0.17

---

build.sbt
default.nix

📦 Updates [com.h2database:h2](https://github.com/h2database/h2database) from `2.2.222` to `2.2.224`

h2: 2.2.222 -> 2.2.224

---

build.sbt
default.nix

📦 Updates 
from `2.0.17` to `2.0.18`
📜 [GitHub Release Notes](https://github.com/zio/zio/releases/tag/v2.0.18) - [Version Diff](https://github.com/zio/zio/compare/v2.0.17...v2.0.18)

zio: 2.0.17 -> 2.0.18

---

modules/producers/src/main/scala/sectery/producers/Grab.scala

This drops `randomGrabbedNick`, which was used to first randomize the nick selection to fairly randomize the pool.
This change avoids over-indexing on messages from nicks with relatively few grabs.

When quoting a random nick, just pick a message

---

build.sbt
default.nix

📦 Updates 
from `2.0.18` to `2.0.19`
📜 [GitHub Release Notes](https://github.com/zio/zio/releases/tag/v2.0.19) - [Version Diff](https://github.com/zio/zio/compare/v2.0.18...v2.0.19)

zio: 2.0.18 -> 2.0.19

---

build.sbt
default.nix

📦 Updates 
from `2.0.19` to `2.0.20`
📜 [GitHub Release Notes](https://github.com/zio/zio/releases/tag/v2.0.20) - [Version Diff](https://github.com/zio/zio/compare/v2.0.19...v2.0.20)

zio: 2.0.19 -> 2.0.20

---

build.sbt
default.nix

📦 Updates 
from `2.0.20` to `2.0.21`
📜 [GitHub Release Notes](https://github.com/zio/zio/releases/tag/v2.0.21) - [Version Diff](https://github.com/zio/zio/compare/v2.0.20...v2.0.21)

zio: 2.0.20 -> 2.0.21

---

default.nix

See https://github.com/NixOS/nixpkgs/commits/nixos-unstable/

Update to lastest nixos-unstable

---

build.sbt
default.nix

📦 Updates 
from `2.0.21` to `2.0.22`
📜 [GitHub Release Notes](https://github.com/zio/zio/releases/tag/v2.0.22) - [Version Diff](https://github.com/zio/zio/compare/v2.0.21...v2.0.22)

zio: 2.0.21 -> 2.0.22

---

build.sbt
default.nix

📦 Updates 
from `2.0.22` to `2.1.1`
📜 [GitHub Release Notes](https://github.com/zio/zio/releases/tag/v2.1.1) - [Version Diff](https://github.com/zio/zio/compare/v2.0.22...v2.1.1)

zio: 2.0.22 -> 2.1.1

---

build.sbt
default.nix

📦 Updates [ch.qos.logback:logback-classic](https://github.com/qos-ch/logback) from `1.3.14` to `1.5.6`

logback-classic: 1.3.14 -> 1.5.6

---

build.sbt
default.nix

📦 Updates [dev.zio:zio](https://github.com/zio/zio) from `2.1.1` to `2.1.2`
📜 [GitHub Release Notes](https://github.com/zio/zio/releases/tag/v2.1.2) - [Version Diff](https://github.com/zio/zio/compare/v2.1.1...v2.1.2)

zio: 2.1.1 -> 2.1.2

---

build.sbt
default.nix

📦 Updates [dev.zio:zio-json](https://github.com/zio/zio-json) from `0.6.2` to `0.7.0`
📜 [GitHub Release Notes](https://github.com/zio/zio-json/releases/tag/v0.7.0) - [Version Diff](https://github.com/zio/zio-json/compare/v0.6.2...v0.7.0)

zio-json: 0.6.2 -> 0.7.0

---

build.sbt
default.nix

📦 Updates [dev.zio:zio](https://github.com/zio/zio) from `2.1.2` to `2.1.4`
📜 [GitHub Release Notes](https://github.com/zio/zio/releases/tag/2.1.4) - [GitHub Release Notes](https://github.com/zio/zio/releases/tag/v2.1.4) - [Version Diff](https://github.com/zio/zio/compare/v2.1.2...v2.1.4)

zio: 2.1.2 -> 2.1.4

---

build.sbt
default.nix

📦 Updates [dev.zio:zio](https://github.com/zio/zio) from `2.1.4` to `2.1.5`
📜 [GitHub Release Notes](https://github.com/zio/zio/releases/tag/v2.1.5) - [Version Diff](https://github.com/zio/zio/compare/v2.1.4...v2.1.5)

zio: 2.1.4 -> 2.1.5

---

build.sbt
default.nix

📦 Updates [dev.zio:zio-json](https://github.com/zio/zio-json) from `0.7.0` to `0.7.1`
📜 [GitHub Release Notes](https://github.com/zio/zio-json/releases/tag/v0.7.1) - [Version Diff](https://github.com/zio/zio-json/compare/v0.7.0...v0.7.1)

zio-json: 0.7.0 -> 0.7.1

---

build.sbt
default.nix

📦 Updates [com.h2database:h2](https://github.com/h2database/h2database) from `2.2.224` to `2.3.230`

h2: 2.2.224 -> 2.3.230

---

build.sbt
default.nix

📦 Updates [dev.zio:zio](https://github.com/zio/zio) from `2.1.5` to `2.1.6`
📜 [GitHub Release Notes](https://github.com/zio/zio/releases/tag/v2.1.6) - [Version Diff](https://github.com/zio/zio/compare/v2.1.5...v2.1.6)

zio: 2.1.5 -> 2.1.6

---

build.sbt
default.nix

📦 Updates [org.jsoup:jsoup](https://github.com/jhy/jsoup) from `1.17.2` to `1.18.1`
📜 [Changelog](https://github.com/jhy/jsoup/blob/master/CHANGES.md)

jsoup: 1.17.2 -> 1.18.1

---

build.sbt
default.nix

📦 Updates [com.h2database:h2](https://github.com/h2database/h2database) from `2.3.230` to `2.3.232`

h2: 2.3.230 -> 2.3.232

---

build.sbt
default.nix

📦 Updates [dev.zio:zio-json](https://github.com/zio/zio-json) from `0.7.1` to `0.7.2`
📜 [GitHub Release Notes](https://github.com/zio/zio-json/releases/tag/v0.7.2) - [Version Diff](https://github.com/zio/zio-json/compare/v0.7.1...v0.7.2)

zio-json: 0.7.1 -> 0.7.2

---

build.sbt
default.nix

📦 Updates [dev.zio:zio](https://github.com/zio/zio) from `2.1.8` to `2.1.9`
📜 [GitHub Release Notes](https://github.com/zio/zio/releases/tag/v2.1.9) - [Version Diff](https://github.com/zio/zio/compare/v2.1.8...v2.1.9)

zio: 2.1.8 -> 2.1.9

---

build.sbt
default.nix

📦 Updates [dev.zio:zio-json](https://github.com/zio/zio-json) from `0.7.2` to `0.7.3`
📜 [GitHub Release Notes](https://github.com/zio/zio-json/releases/tag/v0.7.3) - [Version Diff](https://github.com/zio/zio-json/compare/v0.7.2...v0.7.3)

zio-json: 0.7.2 -> 0.7.3
